### ISSUE TITLE
AOCO Datasets

### ISSUE THREAD

**Issue by alexlorenzo** [AllenChen1998/RAD#3]
Hello,

Thanks for your package.
Since I'm in Europe, I cannot access to Baidu and then your dataset AOCO. 
Could you share it on other platform (Kaggle, OneDrive) or by email ?

Kr,

**Comment by Sizhe-Chen** [comment]
Hi, thanks for the interest on our work. AOCO could also be downloaded at this url
https://drive.google.com/drive/folders/1ToW2N_z7nmZEvAuJvqIos3UQsS6dYF8y?usp=sharing
